name: CI

on:
  push:
    branches:
      - "**"

jobs:

  test:
    permissions:
      contents: 'read'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Test
        run: |
          docker run \
            --rm \
            --volume "$(pwd):/src" \
            --workdir /src \
            golang:1.19.4-bullseye go test -shuffle on -race ./...
